default = 'firefox'

[[browsers]]
command = 'firefox-developer-edition'
domains = [
    "github.com",
]

[[browsers]]
command = 'chromium'
domains = [
    'meet.google.com'
]

[[browsers]]
command = 'firefox'
args = [
    '--private-window'
]
domains = [
    "gitlab.com",
]

